#pragma once
#include <cassert>
#include <inttypes.h>
#include <stdio.h>
#include <memory.h>

// For the front end - later
#define WS_EDITOR __declspec(dllexport) 

#define DEBUG_TRACE_EXECUTION


// Instrumentation to help debug the generated code
// To help debug the generated bytecode, we'll add support for dumping the chunk once the compiler finishes
// We had some temporary logging earlier with our hand-authored chunk. Now we will put in some real code so that we can 
// enable it whenever we want

// When this flag is defined, we use our existing debugging functions in the chunk class to print out the chunk's bytecode
#define DEBUG_PRINT_CODE


#define WS_ASSERT(condition) if(!(condition)) __debugbreak()

inline bool IsDigit(char c)
{
	return c >= '0' && c <= '9';
}

inline bool IsAlpha(char c)
{
	return
		c >= 'a' && c <= 'z' ||
		c >= 'A' && c <= 'Z' ||
		c == '_';
}

inline bool IsAlphaNumeric(char c)
{
	return IsDigit(c) || IsAlpha(c);
}


